//! Canonical bytes, and the one place that knows how big they are.
//!
//! The planner in [`super::plan`] needs exact record sizes, and the only way to
//! be exact is to ask the code that writes the bytes. Every line has one
//! renderer here; [`BodySizer`] measures pages by calling those same renderers.
//! A test packs a page, renders it, and asserts the two numbers agree — which
//! is what keeps "estimated size" from quietly becoming a second format.
//!
//! Output is always UTF-8 without a BOM and always LF, on every platform. A
//! generated file whose bytes depend on the host that wrote it cannot be
//! compared, and comparison is the only thing that makes an unchanged file
//! detectable.

use std::fmt::Write as _;

use super::digest::{Digest, HashStream};
use super::model::{ApiRecord, ChildRecord, Scope, ScopePath, TestRecord, TextProjection};
use super::plan::{PageContent, PageName, Records, Slot};
use super::purpose::ExistingPurposes;
use super::{
    encode, TextError, TextResult, BYTES_PER_TOKEN, PURPOSE_MAX_BYTES, SYMBOLS_PATH,
    TEXT_FORMAT_VERSION,
};

/// Every fixed line this module writes, spelled once.
///
/// Constants rather than inline literals because several of them appear in the
/// renderer, the parser, and a size calculation. Three copies of a marker is
/// three places for it to drift.
pub(crate) const MAP_TYPE: &str = "rr-map";
pub(crate) const SYMBOLS_TYPE: &str = "rr-symbols";
pub(crate) const MAP_BANNER: &str = "<!-- generated by rr format 1; edit only the purpose slot -->";
pub(crate) const SYMBOLS_BANNER: &str =
    "<!-- generated by rr format 1; local and fully replaceable -->";
pub(crate) const MERGE_FOOTER: &str = "<!-- rr:merge-conflict: resolve one side, then run `rr map`; never hand-merge generated sections -->";
pub(crate) const SLOT_OPEN: &str = "<!-- rr:slot purpose max=160 -->";
pub(crate) const SLOT_CLOSE: &str = "<!-- /rr:slot -->";
pub(crate) const PURPOSE_HEADING: &str = "## Purpose";
pub(crate) const CHILDREN_HEADING: &str = "## Children";
pub(crate) const API_HEADING: &str = "## API";
pub(crate) const TESTS_HEADING: &str = "## Tests";
pub(crate) const EMPTY_SECTION: &str = "_None._";
pub(crate) const SYMBOLS_TITLE: &str = "# Symbols";
pub(crate) const SYMBOLS_COLUMNS: &str =
    "<!-- columns: symbol<TAB>visibility<TAB>map<TAB>source<TAB>line<TAB>api_hash -->";
pub(crate) const ROUTER_TITLE: &str = "# Repository map: ";
pub(crate) const PAGE_TITLE: &str = "# Repository map part: ";
/// The separator between a name, its signature, and its source link.
const FIELD_SEPARATOR: &str = " — ";

/// The text substituted for purpose content when computing `generated_hash`.
///
/// A fixed sentinel rather than the real bytes, so that editing the one region
/// a human owns does not make the file look tampered with. It is substituted by
/// rendering the body a second time, never by searching the finished body for
/// the purpose text — a search would find the wrong occurrence for a purpose
/// that happens to repeat something else on the page, and would match
/// everywhere at once for an empty one.
pub(crate) const PURPOSE_SENTINEL: &str = "rr:purpose";

/// What kind of artifact a rendered file is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArtifactKind {
    /// A committed `MAP.md` router with a purpose slot.
    Router,
    /// A committed, fully generated overflow page.
    Page,
    /// The local `.rr/SYMBOLS.md`.
    Symbols,
}

/// One artifact, rendered.
#[derive(Debug, Clone)]
pub struct RenderedFile {
    path: String,
    bytes: Vec<u8>,
    kind: ArtifactKind,
    generated_hash: Digest,
}

impl RenderedFile {
    /// The repository-relative path this file belongs at.
    #[must_use]
    pub fn path(&self) -> &str {
        &self.path
    }

    /// The complete canonical bytes.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    #[must_use]
    pub const fn kind(&self) -> ArtifactKind {
        self.kind
    }

    #[must_use]
    pub const fn generated_hash(&self) -> Digest {
        self.generated_hash
    }
}

/// Every artifact of one generation, in publication order.
///
/// The order is part of the contract, not a convenience: local state first,
/// then committed pages bottom-up, then the root router last as the marker that
/// the generation is complete. A crash between two of these leaves files that
/// disagree about `index_hash`, which the next run detects — the one failure
/// mode a multi-file replacement can actually offer.
#[derive(Debug, Clone)]
pub struct RenderedArtifactSet {
    files: Vec<RenderedFile>,
    index_hash: Digest,
    pending_purposes: u32,
}

impl RenderedArtifactSet {
    /// Every file, in the order it must be written.
    #[must_use]
    pub fn files(&self) -> &[RenderedFile] {
        &self.files
    }

    /// The identity every one of these files carries.
    #[must_use]
    pub const fn index_hash(&self) -> Digest {
        self.index_hash
    }

    /// How many routers still hold a seeded, unwritten purpose.
    #[must_use]
    pub const fn pending_purposes(&self) -> u32 {
        self.pending_purposes
    }

    /// The committed map paths this generation expects to exist.
    ///
    /// Staging subtracts this from the set of rr-owned files already on disk to
    /// learn what a removed directory left behind.
    pub fn committed_paths(&self) -> impl Iterator<Item = &str> {
        self.files
            .iter()
            .filter(|file| file.kind != ArtifactKind::Symbols)
            .map(|file| file.path.as_str())
    }
}

impl TextProjection {
    /// Renders every artifact, preserving whatever purposes were handed in.
    ///
    /// # Errors
    /// Returns an error when a record cannot be represented in the grammar —
    /// which, given the projection's own invariants, means the snapshot
    /// contained something this format cannot state rather than that the
    /// caller did anything wrong.
    pub fn render(&self, purposes: &ExistingPurposes) -> crate::Result<RenderedArtifactSet> {
        Ok(self.render_all(purposes)?)
    }

    fn render_all(&self, purposes: &ExistingPurposes) -> TextResult<RenderedArtifactSet> {
        let mut files = Vec::with_capacity(self.scopes.len() + 1);
        let mut pending_purposes = 0_u32;

        files.push(render_symbols(self)?);

        // Deepest scopes first, root last: a router is published only after
        // everything it links to already exists.
        let mut ordered: Vec<&Scope> = self.scopes.iter().collect();
        ordered.sort_by(|left, right| {
            right.path.depth().cmp(&left.path.depth()).then_with(|| {
                left.path
                    .as_str()
                    .as_bytes()
                    .cmp(right.path.as_str().as_bytes())
            })
        });

        for scope in ordered {
            for page in scope.plan.pages() {
                files.push(render_map(
                    self,
                    scope,
                    Page::Overflow(page.name),
                    &page.content,
                    None,
                )?);
            }
            let purpose = purposes.for_map(&scope.path.map_path());
            let purpose = match purpose {
                Some(text) => text.to_owned(),
                None => super::purpose::seed(scope),
            };
            if super::purpose::is_pending(&purpose) {
                pending_purposes += 1;
            }
            files.push(render_map(
                self,
                scope,
                Page::Router,
                scope.plan.router(),
                Some(&purpose),
            )?);
        }

        Ok(RenderedArtifactSet {
            files,
            index_hash: self.index_hash(),
            pending_purposes,
        })
    }
}

/// Which page of a scope is being rendered.
#[derive(Debug, Clone, Copy)]
enum Page {
    Router,
    Overflow(PageName),
}

impl Page {
    /// The `page:` frontmatter value.
    fn label(self) -> String {
        match self {
            Self::Router => "root".to_owned(),
            Self::Overflow(name) => format!("part-{:08}-{:08}", name.level, name.ordinal),
        }
    }

    fn file_name(self) -> String {
        match self {
            Self::Router => super::MAP_FILE_NAME.to_owned(),
            Self::Overflow(name) => name.file_name(),
        }
    }

    const fn kind(self) -> ArtifactKind {
        match self {
            Self::Router => ArtifactKind::Router,
            Self::Overflow(_) => ArtifactKind::Page,
        }
    }
}

/// Renders one map page, frontmatter and all.
fn render_map(
    projection: &TextProjection,
    scope: &Scope,
    page: Page,
    content: &PageContent,
    purpose: Option<&str>,
) -> TextResult<RenderedFile> {
    let body = map_body(scope, page, content, purpose)?;
    let hashed_body = match purpose {
        Some(_) => map_body(scope, page, content, Some(PURPOSE_SENTINEL))?,
        None => body.clone(),
    };

    let mut fields = vec![
        ("type", Value::Text(MAP_TYPE.to_owned())),
        ("format", Value::Number(u64::from(TEXT_FORMAT_VERSION))),
        ("scope", Value::Text(scope.path.as_str().to_owned())),
        ("page", Value::Text(page.label())),
        ("fidelity", Value::Text(scope.fidelity.as_str().to_owned())),
        ("index_hash", Value::Text(projection.index_hash().to_text())),
        ("api_hash", Value::Text(scope.api_hash.to_text())),
        ("generated_hash", Value::Text(String::new())),
        ("tokens", Value::Number(u64::from(token_estimate(&body)))),
        ("budget", Value::Number(u64::from(projection.budget))),
    ];
    let generated_hash = seal(&mut fields, &hashed_body)?;

    let mut out = frontmatter(&fields);
    out.push_str(&body);
    Ok(RenderedFile {
        path: scope.path.join(&page.file_name()),
        bytes: out.into_bytes(),
        kind: page.kind(),
        generated_hash,
    })
}

/// Renders the local symbol index.
fn render_symbols(projection: &TextProjection) -> TextResult<RenderedFile> {
    let mut body = String::new();
    line(&mut body, SYMBOLS_BANNER);
    line(&mut body, SYMBOLS_TITLE);
    line(&mut body, SYMBOLS_COLUMNS);
    for record in &projection.symbols {
        let rendered = format!(
            "{}\t{}\t{}\t{}\t{}\t{}",
            record.encoded_symbol,
            record.visibility,
            record.encoded_map,
            record.anchor,
            record.start_line,
            record.api_hash.to_text()
        );
        // The anchor is the one field carrying arbitrary repository text, and
        // a tab or newline inside it would silently invent a column or a row.
        if rendered.contains('\n') || rendered.matches('\t').count() != 5 {
            return Err(TextError::Record {
                reason: "a symbol record contains a tab or newline of its own",
            });
        }
        line(&mut body, &rendered);
    }

    let mut fields = vec![
        ("type", Value::Text(SYMBOLS_TYPE.to_owned())),
        ("format", Value::Number(u64::from(TEXT_FORMAT_VERSION))),
        (
            "fidelity",
            Value::Text(projection.fidelity().as_str().to_owned()),
        ),
        ("index_hash", Value::Text(projection.index_hash().to_text())),
        ("generated_hash", Value::Text(String::new())),
        ("symbols", Value::Number(projection.symbols.len() as u64)),
    ];
    let generated_hash = seal(&mut fields, &body)?;

    let mut out = frontmatter(&fields);
    out.push_str(&body);
    Ok(RenderedFile {
        path: SYMBOLS_PATH.to_owned(),
        bytes: out.into_bytes(),
        kind: ArtifactKind::Symbols,
        generated_hash,
    })
}

/// A frontmatter value in the rr-owned YAML subset.
///
/// Two shapes, because the subset has two: a double-quoted JSON string and an
/// unsigned base-10 integer. Anything a caller might want that is not one of
/// these is something the format does not have.
pub(crate) enum Value {
    Text(String),
    Number(u64),
}

impl Value {
    fn render(&self) -> String {
        match self {
            Self::Text(text) => quote(text),
            Self::Number(number) => number.to_string(),
        }
    }
}

/// Quotes a string the way the subset requires: JSON escapes, nothing else.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            control if control < ' ' || control == '\u{7f}' => {
                let _ = write!(out, "\\u{:04x}", control as u32);
            }
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

fn frontmatter(fields: &[(&str, Value)]) -> String {
    let mut out = String::from("---\n");
    for (key, value) in fields {
        let _ = writeln!(out, "{key}: {}", value.render());
    }
    out.push_str("---\n");
    out
}

/// The two frontmatter keys a generated hash cannot cover.
///
/// `generated_hash` cannot cover itself, and `tokens` measures the body that is
/// hashed alongside it. Everything else is covered.
const UNHASHED_FIELDS: [&str; 2] = ["tokens", "generated_hash"];

/// Hashes the immutable frontmatter plus the body.
///
/// Takes the *complete* field list and does the excluding itself. An earlier
/// version relied on being called before the excluded fields existed, which
/// silently excluded every field appended afterwards as well — and a renderer
/// that excludes a field the reader includes writes files that verify against
/// nothing. The rule is spelled here, once, and [`super::parse`] calls this
/// same function with the fields it read.
pub(crate) fn generated_hash_of(fields: &[(&str, Value)], body: &str) -> Digest {
    let hashed: Vec<&(&str, Value)> = fields
        .iter()
        .filter(|(key, _)| !UNHASHED_FIELDS.contains(key))
        .collect();
    let mut stream = HashStream::new("generated");
    stream.count(hashed.len());
    for (key, value) in hashed {
        stream.text(key);
        stream.text(&value.render());
    }
    stream.text(body);
    stream.finish()
}

/// Computes `generated_hash` and writes it into the field it belongs to.
///
/// The placeholder must already be in the list, in its published position, so
/// that the hash is taken over the frontmatter the file will actually carry.
fn seal(fields: &mut [(&str, Value)], body: &str) -> TextResult<Digest> {
    let digest = generated_hash_of(fields, body);
    let slot = fields
        .iter_mut()
        .find(|(key, _)| *key == "generated_hash")
        .ok_or(TextError::Frontmatter {
            reason: "a rendered artifact has no generated_hash field",
        })?;
    slot.1 = Value::Text(digest.to_text());
    Ok(digest)
}

/// `ceil(body_bytes / 4)`, which is why the frontmatter is excluded: a token
/// count that counted itself could never settle.
fn token_estimate(body: &str) -> u32 {
    let bytes = u32::try_from(body.len()).unwrap_or(u32::MAX);
    bytes.div_ceil(BYTES_PER_TOKEN)
}

fn line(out: &mut String, text: &str) {
    out.push_str(text);
    out.push('\n');
}

/// The body of one map page.
fn map_body(
    scope: &Scope,
    page: Page,
    content: &PageContent,
    purpose: Option<&str>,
) -> TextResult<String> {
    let records = scope.records();
    let mut out = String::new();
    line(&mut out, MAP_BANNER);
    match page {
        Page::Router => line(&mut out, &format!("{ROUTER_TITLE}{}", scope.path.as_str())),
        Page::Overflow(_) => line(&mut out, &format!("{PAGE_TITLE}{}", scope.path.as_str())),
    }

    if let Some(text) = purpose {
        out.push('\n');
        line(&mut out, PURPOSE_HEADING);
        line(&mut out, SLOT_OPEN);
        line(&mut out, text);
        line(&mut out, SLOT_CLOSE);
    }

    let (children, api, tests) = records.split(&content.records);

    out.push('\n');
    line(&mut out, CHILDREN_HEADING);
    if children.is_empty() && content.links.is_empty() {
        line(&mut out, EMPTY_SECTION);
    } else {
        for child in &records.children[children] {
            line(&mut out, &child_line(child));
        }
        for name in &content.links {
            line(&mut out, &page_link_line(*name));
        }
    }

    out.push('\n');
    line(&mut out, API_HEADING);
    if api.is_empty() {
        line(&mut out, EMPTY_SECTION);
    } else {
        let mut current_file: Option<&str> = None;
        for record in &records.api[api] {
            if current_file != Some(record.path.as_str()) {
                line(&mut out, &api_heading(record));
                current_file = Some(record.path.as_str());
            }
            line(&mut out, &api_line(record));
        }
    }

    out.push('\n');
    line(&mut out, TESTS_HEADING);
    if tests.is_empty() {
        line(&mut out, EMPTY_SECTION);
    } else {
        for record in &records.tests[tests] {
            line(&mut out, &test_line(record));
        }
    }

    out.push('\n');
    line(&mut out, MERGE_FOOTER);

    if out.contains('\r') || out.contains('\u{0}') {
        return Err(TextError::Newline {
            reason: "a rendered record contains a carriage return or NUL",
        });
    }
    Ok(out)
}

pub(crate) fn child_line(child: &ChildRecord) -> String {
    let destination =
        encode::destination(&format!("{}/{}", child.name, super::MAP_FILE_NAME), None);
    format!("- [{}](<{destination}>)", encode::escape_label(&child.name))
}

pub(crate) fn api_heading(record: &ApiRecord) -> String {
    format!("### {}", encode::escape_label(&record.path))
}

pub(crate) fn api_line(record: &ApiRecord) -> String {
    let destination = encode::destination(&record.file_name, Some(&record.anchor_name));
    format!(
        "- {}{FIELD_SEPARATOR}{}{FIELD_SEPARATOR}[source](<{destination}>)",
        encode::code_span(&record.name),
        encode::code_span(&record.signature)
    )
}

pub(crate) fn test_line(record: &TestRecord) -> String {
    let (file, symbol) = record.local_target();
    let destination = encode::destination(&file, Some(&symbol));
    format!(
        "- [{}](<{destination}>)",
        encode::escape_label(&record.anchor())
    )
}

pub(crate) fn page_link_line(name: PageName) -> String {
    let file = name.file_name();
    format!(
        "- [{}](<{}>)",
        encode::escape_label(&file),
        encode::destination(&file, None)
    )
}

/// Body bytes of a page holding nothing, for this scope.
///
/// Measured by rendering rather than by adding up constants, so that a change
/// to the shell cannot leave the planner working from last month's arithmetic.
fn empty_body_bytes(scope: &ScopePath, purpose: Option<&str>) -> usize {
    let mut out = String::new();
    line(&mut out, MAP_BANNER);
    let title = if purpose.is_some() {
        ROUTER_TITLE
    } else {
        PAGE_TITLE
    };
    line(&mut out, &format!("{title}{}", scope.as_str()));
    if let Some(text) = purpose {
        out.push('\n');
        line(&mut out, PURPOSE_HEADING);
        line(&mut out, SLOT_OPEN);
        line(&mut out, text);
        line(&mut out, SLOT_CLOSE);
    }
    for heading in [CHILDREN_HEADING, API_HEADING, TESTS_HEADING] {
        out.push('\n');
        line(&mut out, heading);
        line(&mut out, EMPTY_SECTION);
    }
    out.push('\n');
    line(&mut out, MERGE_FOOTER);
    out.len()
}

/// The body bytes a router spends before holding any record.
///
/// Includes the full reserved purpose, never the purpose actually present: page
/// planning that moved records when somebody edited prose would republish half
/// the repository for a sentence.
pub(crate) fn router_overhead(scope: &ScopePath) -> usize {
    empty_body_bytes(scope, Some(&"p".repeat(PURPOSE_MAX_BYTES)))
}

/// The body bytes an overflow page spends before holding any record.
pub(crate) fn page_overhead(scope: &ScopePath) -> usize {
    empty_body_bytes(scope, None)
}

/// The rendered size of one page-link line, which every page name shares.
///
/// Fixed width by construction: the level and ordinal are zero-padded to eight
/// digits precisely so that the planner can price a link before it knows how
/// many links there will be.
fn page_link_line_bytes() -> usize {
    page_link_line(PageName {
        level: 0,
        ordinal: 0,
    })
    .len()
        + 1
}

/// The bytes `count` page links add to a `## Children` section holding nothing
/// else.
///
/// The first link also removes the section's `_None._` line, which is why this
/// is not simply a multiplication.
pub(crate) fn link_list_bytes(count: usize) -> usize {
    if count == 0 {
        return 0;
    }
    (count * page_link_line_bytes()).saturating_sub(EMPTY_SECTION.len() + 1)
}

/// Measures a page as records are added to it.
///
/// Exists so the planner never guesses. Every number it produces comes from a
/// real rendered line, and `sizer.bytes()` after pushing a range equals the
/// length of the body that range renders to.
#[derive(Clone)]
pub(crate) struct BodySizer<'a> {
    records: Records<'a>,
    bytes: usize,
    /// The file whose `###` heading is already on this page, if any.
    current_file: Option<&'a str>,
    children_used: bool,
    api_used: bool,
    tests_used: bool,
}

impl<'a> BodySizer<'a> {
    pub(crate) fn new(records: Records<'a>) -> Self {
        Self {
            records,
            bytes: 0,
            current_file: None,
            children_used: false,
            api_used: false,
            tests_used: false,
        }
    }

    /// Bytes this page would occupy with `links` page links appended.
    pub(crate) fn bytes_with_links(&self, links: usize) -> usize {
        if links == 0 {
            return self.bytes;
        }
        let total = links * page_link_line_bytes();
        self.bytes
            + if self.children_used {
                total
            } else {
                total.saturating_sub(EMPTY_SECTION.len() + 1)
            }
    }

    /// Whether pushing `index` keeps the page within `capacity`, allowing for
    /// `links` page links that will be appended afterwards.
    pub(crate) fn would_fit(&self, index: usize, capacity: usize, links: usize) -> bool {
        let mut next = self.clone();
        next.push(index);
        next.bytes_with_links(links) <= capacity
    }

    /// Adds a record to the page.
    pub(crate) fn push(&mut self, index: usize) {
        self.bytes += self.cost_of(index);
        match self.records.at(index) {
            Slot::Child(_) => self.children_used = true,
            Slot::Api(position) => {
                self.api_used = true;
                self.current_file = Some(self.records.api[position].path.as_str());
            }
            Slot::Test(_) => self.tests_used = true,
        }
    }

    /// What one record costs on this page right now.
    ///
    /// Context-dependent on purpose: the first record in a section replaces its
    /// `_None._` line, and the first record of a file also pays for the `###`
    /// heading that a later record of the same file rides along with.
    fn cost_of(&self, index: usize) -> usize {
        let empty_line = EMPTY_SECTION.len() + 1;
        match self.records.at(index) {
            Slot::Child(position) => {
                let cost = child_line(&self.records.children[position]).len() + 1;
                first_in_section(cost, self.children_used, empty_line)
            }
            Slot::Api(position) => {
                let record = &self.records.api[position];
                let mut cost = api_line(record).len() + 1;
                if self.current_file != Some(record.path.as_str()) {
                    cost += api_heading(record).len() + 1;
                }
                first_in_section(cost, self.api_used, empty_line)
            }
            Slot::Test(position) => {
                let cost = test_line(&self.records.tests[position]).len() + 1;
                first_in_section(cost, self.tests_used, empty_line)
            }
        }
    }
}

/// The first record of a section also removes that section's `_None._` line.
fn first_in_section(cost: usize, section_used: bool, empty_line: usize) -> usize {
    if section_used {
        cost
    } else {
        cost.saturating_sub(empty_line)
    }
}
