//! Canonical bytes, and the one place that knows how big they are.
//!
//! The planner in [`super::plan`] needs exact record sizes, so [`BodySizer`]
//! measures pages by calling the same renderers that write them.
//!
//! Output is UTF-8 without a BOM and LF on every platform: bytes that depend on
//! the host cannot be compared, and comparison is what detects an unchanged
//! file.

use std::fmt::Write as _;

use super::digest::{Digest, HashStream};
use super::model::{ApiRecord, ChildRecord, Scope, ScopePath, TestRecord, TextProjection};
use super::plan::{PageContent, Records, Slot};
use super::purpose::ExistingPurposes;
use super::{
    encode, TextError, TextResult, BYTES_PER_TOKEN, PURPOSE_MAX_BYTES, SYMBOLS_PATH,
    TEXT_FORMAT_VERSION,
};

/// Every fixed line this module writes, spelled once.
///
/// Constants rather than inline literals because several of them appear in the
/// renderer, the parser, and a size calculation. Three copies of a marker is
/// three places for it to drift.
pub(crate) const MAP_TYPE: &str = "rr-map";
pub(crate) const SYMBOLS_TYPE: &str = "rr-symbols";
pub(crate) const MERGE_FOOTER: &str = "<!-- rr:merge-conflict: resolve one side, then run `rr map`; never hand-merge generated sections -->";
pub(crate) const SLOT_OPEN: &str = "<!-- rr:slot purpose max=160 -->";
pub(crate) const SLOT_CLOSE: &str = "<!-- /rr:slot -->";
pub(crate) const PURPOSE_HEADING: &str = "## Purpose";
pub(crate) const CHILDREN_HEADING: &str = "## Children";
pub(crate) const API_HEADING: &str = "## API";
pub(crate) const TESTS_HEADING: &str = "## Tests";
pub(crate) const EMPTY_SECTION: &str = "_None._";
pub(crate) const SYMBOLS_TITLE: &str = "# Symbols";
pub(crate) const SYMBOLS_COLUMNS: &str =
    "<!-- columns: symbol<TAB>visibility<TAB>map<TAB>source<TAB>line<TAB>api_hash -->";
pub(crate) const ROUTER_TITLE: &str = "# Repository map: ";
pub(crate) const PAGE_TITLE: &str = "# Repository map part: ";
/// The separator between a name, its signature, and its source link.
const FIELD_SEPARATOR: &str = " — ";

/// The banner a map of this format version carries.
pub(crate) fn map_banner(format: u32) -> String {
    format!("<!-- generated by rr format {format}; edit only the purpose slot -->")
}

/// The banner a symbol index of this format version carries.
pub(crate) fn symbols_banner(format: u32) -> String {
    format!("<!-- generated by rr format {format}; local and fully replaceable -->")
}

/// Which section an omission line belongs to.
///
/// Named in the line itself — Radar's `public symbols` — so a reader who
/// opens one section is not told about another.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum OmittedKind {
    Children,
    Api,
    Tests,
}

impl OmittedKind {
    pub(crate) const fn noun(self) -> &'static str {
        match self {
            Self::Children => "children",
            Self::Api => "public symbols",
            Self::Tests => "tests",
        }
    }
}

/// The last line of a section that did not fit.
pub(crate) fn omission_line(kind: OmittedKind, count: usize) -> String {
    format!("+ {count} more {} omitted by the map budget", kind.noun())
}

/// The text substituted for purpose content when computing `generated_hash`.
///
/// A fixed sentinel, so editing the one region a human owns does not make the
/// file look tampered with. Substituted by rendering the body a second time,
/// never by searching the finished body — a search would hit the wrong
/// occurrence, and every occurrence for an empty purpose.
pub(crate) const PURPOSE_SENTINEL: &str = "rr:purpose";

/// What kind of artifact a rendered file is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ArtifactKind {
    /// A committed `MAP.md` router with a purpose slot.
    Router,
    /// A committed, fully generated overflow page.
    Page,
    /// The local `.rr/SYMBOLS.md`.
    Symbols,
}

/// One artifact, rendered.
#[derive(Debug, Clone)]
pub struct RenderedFile {
    path: String,
    bytes: Vec<u8>,
    kind: ArtifactKind,
    generated_hash: Digest,
}

impl RenderedFile {
    /// The repository-relative path this file belongs at.
    #[must_use]
    pub fn path(&self) -> &str {
        &self.path
    }

    /// The complete canonical bytes.
    #[must_use]
    pub fn bytes(&self) -> &[u8] {
        &self.bytes
    }

    #[must_use]
    pub const fn kind(&self) -> ArtifactKind {
        self.kind
    }

    #[must_use]
    pub const fn generated_hash(&self) -> Digest {
        self.generated_hash
    }
}

/// Every artifact of one generation, in publication order.
///
/// The order is part of the contract, not a convenience: local state first,
/// then committed pages bottom-up, then the root router last as the marker that
/// the generation is complete. A crash between two of these leaves files that
/// disagree about `index_hash`, which the next run detects — the one failure
/// mode a multi-file replacement can actually offer.
#[derive(Debug, Clone)]
pub struct RenderedArtifactSet {
    files: Vec<RenderedFile>,
    index_hash: Digest,
    pending_purposes: u32,
}

impl RenderedArtifactSet {
    /// Every file, in the order it must be written.
    #[must_use]
    pub fn files(&self) -> &[RenderedFile] {
        &self.files
    }

    /// The identity every one of these files carries.
    #[must_use]
    pub const fn index_hash(&self) -> Digest {
        self.index_hash
    }

    /// How many routers still hold a seeded, unwritten purpose.
    #[must_use]
    pub const fn pending_purposes(&self) -> u32 {
        self.pending_purposes
    }

    /// The committed map paths this generation expects to exist.
    ///
    /// Staging subtracts this from the set of rr-owned files already on disk to
    /// learn what a removed directory left behind.
    pub fn committed_paths(&self) -> impl Iterator<Item = &str> {
        self.files
            .iter()
            .filter(|file| file.kind != ArtifactKind::Symbols)
            .map(|file| file.path.as_str())
    }
}

impl TextProjection {
    /// Renders every artifact, preserving whatever purposes were handed in.
    ///
    /// # Errors
    /// Returns an error when a record cannot be represented in the grammar —
    /// which, given the projection's own invariants, means the snapshot
    /// contained something this format cannot state rather than that the
    /// caller did anything wrong.
    pub fn render(&self, purposes: &ExistingPurposes) -> crate::Result<RenderedArtifactSet> {
        Ok(self.render_all(purposes)?)
    }

    fn render_all(&self, purposes: &ExistingPurposes) -> TextResult<RenderedArtifactSet> {
        let mut files = Vec::with_capacity(self.scopes.len() + 1);
        let mut pending_purposes = 0_u32;

        files.push(render_symbols(self)?);

        let mut ordered: Vec<&Scope> = self.scopes.iter().collect();
        ordered.sort_by(|left, right| {
            right.path.depth().cmp(&left.path.depth()).then_with(|| {
                left.path
                    .as_str()
                    .as_bytes()
                    .cmp(right.path.as_str().as_bytes())
            })
        });

        for scope in ordered {
            let purpose = purposes.for_map(&scope.path.map_path());
            let purpose = match purpose {
                Some(text) => text.to_owned(),
                None => super::purpose::seed(scope),
            };
            if super::purpose::is_pending(&purpose) {
                pending_purposes += 1;
            }
            files.push(render_map(self, scope, scope.plan.router(), &purpose)?);
        }

        Ok(RenderedArtifactSet {
            files,
            index_hash: self.index_hash(),
            pending_purposes,
        })
    }
}

/// Renders one scope's `MAP.md`, frontmatter and all.
fn render_map(
    projection: &TextProjection,
    scope: &Scope,
    content: &PageContent,
    purpose: &str,
) -> TextResult<RenderedFile> {
    let body = map_body(scope, content, purpose)?;
    let hashed_body = map_body(scope, content, PURPOSE_SENTINEL)?;

    let mut fields = vec![
        ("type", Value::Text(MAP_TYPE.to_owned())),
        ("format", Value::Number(u64::from(TEXT_FORMAT_VERSION))),
        ("scope", Value::Text(scope.path.as_str().to_owned())),
        ("page", Value::Text("root".to_owned())),
        ("fidelity", Value::Text(scope.fidelity.as_str().to_owned())),
        ("index_hash", Value::Text(projection.index_hash().to_text())),
        ("api_hash", Value::Text(scope.api_hash.to_text())),
        ("generated_hash", Value::Text(String::new())),
        ("tokens", Value::Number(u64::from(token_estimate(&body)))),
        ("budget", Value::Number(u64::from(projection.budget))),
    ];
    let generated_hash = seal(&mut fields, &hashed_body)?;

    let mut out = frontmatter(&fields);
    out.push_str(&body);
    Ok(RenderedFile {
        path: scope.path.join(super::MAP_FILE_NAME),
        bytes: out.into_bytes(),
        kind: ArtifactKind::Router,
        generated_hash,
    })
}

/// Renders the local symbol index.
fn render_symbols(projection: &TextProjection) -> TextResult<RenderedFile> {
    let mut body = String::new();
    line(&mut body, &symbols_banner(TEXT_FORMAT_VERSION));
    line(&mut body, SYMBOLS_TITLE);
    line(&mut body, SYMBOLS_COLUMNS);
    for record in &projection.symbols {
        let rendered = format!(
            "{}\t{}\t{}\t{}\t{}\t{}",
            record.encoded_symbol,
            record.visibility,
            record.encoded_map,
            record.anchor,
            record.start_line,
            record.api_hash.to_text()
        );

        if rendered.contains('\n') || rendered.matches('\t').count() != 5 {
            return Err(TextError::Record {
                reason: "a symbol record contains a tab or newline of its own",
            });
        }
        line(&mut body, &rendered);
    }

    let mut fields = vec![
        ("type", Value::Text(SYMBOLS_TYPE.to_owned())),
        ("format", Value::Number(u64::from(TEXT_FORMAT_VERSION))),
        (
            "fidelity",
            Value::Text(projection.fidelity().as_str().to_owned()),
        ),
        ("index_hash", Value::Text(projection.index_hash().to_text())),
        ("generated_hash", Value::Text(String::new())),
        ("symbols", Value::Number(projection.symbols.len() as u64)),
    ];
    let generated_hash = seal(&mut fields, &body)?;

    let mut out = frontmatter(&fields);
    out.push_str(&body);
    Ok(RenderedFile {
        path: SYMBOLS_PATH.to_owned(),
        bytes: out.into_bytes(),
        kind: ArtifactKind::Symbols,
        generated_hash,
    })
}

/// A frontmatter value in the rr-owned YAML subset.
///
/// Two shapes, because the subset has two: a double-quoted JSON string and an
/// unsigned base-10 integer. Anything a caller might want that is not one of
/// these is something the format does not have.
pub(crate) enum Value {
    Text(String),
    Number(u64),
}

impl Value {
    fn render(&self) -> String {
        match self {
            Self::Text(text) => quote(text),
            Self::Number(number) => number.to_string(),
        }
    }
}

/// Quotes a string the way the subset requires: JSON escapes, nothing else.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            control if control < ' ' || control == '\u{7f}' => {
                let _ = write!(out, "\\u{:04x}", control as u32);
            }
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

fn frontmatter(fields: &[(&str, Value)]) -> String {
    let mut out = String::from("---\n");
    for (key, value) in fields {
        let _ = writeln!(out, "{key}: {}", value.render());
    }
    out.push_str("---\n");
    out
}

/// The two frontmatter keys a generated hash cannot cover.
///
/// `generated_hash` cannot cover itself, and `tokens` measures the body that is
/// hashed alongside it. Everything else is covered.
const UNHASHED_FIELDS: [&str; 2] = ["tokens", "generated_hash"];

/// Hashes the immutable frontmatter plus the body.
///
/// Takes the *complete* field list and excludes [`UNHASHED_FIELDS`] itself,
/// rather than relying on being called before those fields exist. A renderer
/// that excludes a field the reader includes writes files that verify against
/// nothing, so the rule lives here once and [`super::parse`] calls the same
/// function with the fields it read.
pub(crate) fn generated_hash_of(fields: &[(&str, Value)], body: &str) -> Digest {
    let format = fields
        .iter()
        .find_map(|(key, value)| match (*key, value) {
            ("format", Value::Number(number)) => u32::try_from(*number).ok(),
            _ => None,
        })
        .unwrap_or(TEXT_FORMAT_VERSION);
    let hashed: Vec<&(&str, Value)> = fields
        .iter()
        .filter(|(key, _)| !UNHASHED_FIELDS.contains(key))
        .collect();
    let mut stream = HashStream::with_format("generated", format);
    stream.count(hashed.len());
    for (key, value) in hashed {
        stream.text(key);
        stream.text(&value.render());
    }
    stream.text(body);
    stream.finish()
}

/// Computes `generated_hash` and writes it into the field it belongs to.
///
/// The placeholder must already be in the list, in its published position, so
/// that the hash is taken over the frontmatter the file will actually carry.
fn seal(fields: &mut [(&str, Value)], body: &str) -> TextResult<Digest> {
    let digest = generated_hash_of(fields, body);
    let slot = fields
        .iter_mut()
        .find(|(key, _)| *key == "generated_hash")
        .ok_or(TextError::Frontmatter {
            reason: "a rendered artifact has no generated_hash field",
        })?;
    slot.1 = Value::Text(digest.to_text());
    Ok(digest)
}

/// `ceil(body_bytes / 4)`, which is why the frontmatter is excluded: a token
/// count that counted itself could never settle.
fn token_estimate(body: &str) -> u32 {
    let bytes = u32::try_from(body.len()).unwrap_or(u32::MAX);
    bytes.div_ceil(BYTES_PER_TOKEN)
}

fn line(out: &mut String, text: &str) {
    out.push_str(text);
    out.push('\n');
}

/// The body of one router.
fn map_body(scope: &Scope, content: &PageContent, purpose: &str) -> TextResult<String> {
    let records = scope.records();
    let mut out = String::new();
    line(&mut out, &map_banner(TEXT_FORMAT_VERSION));
    line(&mut out, &format!("{ROUTER_TITLE}{}", scope.path.as_str()));

    out.push('\n');
    line(&mut out, PURPOSE_HEADING);
    line(&mut out, SLOT_OPEN);
    line(&mut out, purpose);
    line(&mut out, SLOT_CLOSE);

    out.push('\n');
    line(&mut out, CHILDREN_HEADING);
    write_section(
        &mut out,
        records.children[content.children.clone()]
            .iter()
            .map(child_line),
        content.omitted_children,
        OmittedKind::Children,
    );

    out.push('\n');
    line(&mut out, API_HEADING);
    if content.api.is_empty() && content.omitted_api == 0 {
        line(&mut out, EMPTY_SECTION);
    } else {
        let mut current_file: Option<&str> = None;
        for record in &records.api[content.api.clone()] {
            if current_file != Some(record.path.as_str()) {
                line(&mut out, &api_heading(record));
                current_file = Some(record.path.as_str());
            }
            line(&mut out, &api_line(record));
        }
        if content.omitted_api > 0 {
            line(
                &mut out,
                &omission_line(OmittedKind::Api, content.omitted_api),
            );
        }
    }

    out.push('\n');
    line(&mut out, TESTS_HEADING);
    write_section(
        &mut out,
        records.tests[content.tests.clone()].iter().map(test_line),
        content.omitted_tests,
        OmittedKind::Tests,
    );

    out.push('\n');
    line(&mut out, MERGE_FOOTER);

    if out.contains('\r') || out.contains('\u{0}') {
        return Err(TextError::Newline {
            reason: "a rendered record contains a carriage return or NUL",
        });
    }
    Ok(out)
}

fn write_section(
    out: &mut String,
    lines: impl IntoIterator<Item = String>,
    omitted: usize,
    kind: OmittedKind,
) {
    let mut empty = true;
    for rendered in lines {
        line(out, &rendered);
        empty = false;
    }
    if omitted > 0 {
        line(out, &omission_line(kind, omitted));
    } else if empty {
        line(out, EMPTY_SECTION);
    }
}

pub(crate) fn child_line(child: &ChildRecord) -> String {
    let destination =
        encode::destination(&format!("{}/{}", child.name, super::MAP_FILE_NAME), None);
    format!("- [{}](<{destination}>)", encode::escape_label(&child.name))
}

pub(crate) fn api_heading(record: &ApiRecord) -> String {
    format!("### {}", encode::escape_label(&record.path))
}

pub(crate) fn api_line(record: &ApiRecord) -> String {
    let destination = encode::destination(&record.file_name, Some(&record.anchor_name));
    format!(
        "- {}{FIELD_SEPARATOR}{}{FIELD_SEPARATOR}[source](<{destination}>)",
        encode::code_span(&record.name),
        encode::code_span(&record.signature)
    )
}

pub(crate) fn test_line(record: &TestRecord) -> String {
    let (file, symbol) = record.local_target();
    let destination = encode::destination(&file, Some(&symbol));
    format!(
        "- [{}](<{destination}>)",
        encode::escape_label(&record.anchor())
    )
}

/// Body bytes of a router holding nothing, for this scope.
///
/// Measured by rendering rather than by adding up constants, so that a change
/// to the shell cannot leave the planner working from last month's arithmetic.
fn empty_body_bytes(scope: &ScopePath, purpose: &str) -> usize {
    let mut out = String::new();
    line(&mut out, &map_banner(TEXT_FORMAT_VERSION));
    line(&mut out, &format!("{ROUTER_TITLE}{}", scope.as_str()));
    out.push('\n');
    line(&mut out, PURPOSE_HEADING);
    line(&mut out, SLOT_OPEN);
    line(&mut out, purpose);
    line(&mut out, SLOT_CLOSE);
    for heading in [CHILDREN_HEADING, API_HEADING, TESTS_HEADING] {
        out.push('\n');
        line(&mut out, heading);
        line(&mut out, EMPTY_SECTION);
    }
    out.push('\n');
    line(&mut out, MERGE_FOOTER);
    out.len()
}

/// The body bytes a router spends before holding any record.
///
/// Includes the full reserved purpose, never the purpose actually present: page
/// planning that moved records when somebody edited prose would republish half
/// the repository for a sentence.
pub(crate) fn router_overhead(scope: &ScopePath) -> usize {
    empty_body_bytes(scope, &"p".repeat(PURPOSE_MAX_BYTES))
}

/// Measures a page as records are added to it.
///
/// Exists so the planner never guesses. Every number it produces comes from a
/// real rendered line, and `sizer.bytes()` after pushing a range equals the
/// length of the body that range renders to.
#[derive(Clone)]
pub(crate) struct BodySizer<'a> {
    records: Records<'a>,
    bytes: usize,
    /// The file whose `###` heading is already on this page, if any.
    current_file: Option<&'a str>,
    children_used: bool,
    api_used: bool,
    tests_used: bool,
}

impl<'a> BodySizer<'a> {
    pub(crate) fn new(records: Records<'a>) -> Self {
        Self {
            records,
            bytes: 0,
            current_file: None,
            children_used: false,
            api_used: false,
            tests_used: false,
        }
    }

    pub(crate) const fn bytes(&self) -> usize {
        self.bytes
    }

    /// Adds a record to the page.
    pub(crate) fn push(&mut self, index: usize) {
        self.bytes += self.cost_of(index);
        match self.records.at(index) {
            Slot::Child(_) => self.children_used = true,
            Slot::Api(position) => {
                self.api_used = true;
                self.current_file = Some(self.records.api[position].path.as_str());
            }
            Slot::Test(_) => self.tests_used = true,
        }
    }

    /// What one record costs on this page right now.
    ///
    /// Context-dependent on purpose: the first record in a section replaces its
    /// `_None._` line, and the first record of a file also pays for the `###`
    /// heading that a later record of the same file rides along with.
    fn cost_of(&self, index: usize) -> usize {
        let empty_line = EMPTY_SECTION.len() + 1;
        match self.records.at(index) {
            Slot::Child(position) => {
                let cost = child_line(&self.records.children[position]).len() + 1;
                first_in_section(cost, self.children_used, empty_line)
            }
            Slot::Api(position) => {
                let record = &self.records.api[position];
                let mut cost = api_line(record).len() + 1;
                if self.current_file != Some(record.path.as_str()) {
                    cost += api_heading(record).len() + 1;
                }
                first_in_section(cost, self.api_used, empty_line)
            }
            Slot::Test(position) => {
                let cost = test_line(&self.records.tests[position]).len() + 1;
                first_in_section(cost, self.tests_used, empty_line)
            }
        }
    }
}

/// The first record of a section also removes that section's `_None._` line.
fn first_in_section(cost: usize, section_used: bool, empty_line: usize) -> usize {
    if section_used {
        cost
    } else {
        cost.saturating_sub(empty_line)
    }
}
