//! `.rr/ROUTES.md`: the routes this repository has already resolved.
//!
//! Everything else under `text/` is *derived* — one snapshot in, one set of
//! bytes out, reproducible from the index alone. This file is the exception: it
//! is **learned**, and nothing can regenerate it except asking the questions
//! again. Two rules follow, and they are why this module looks different from
//! its neighbours.
//!
//! - A damaged file is discarded rather than repaired, because there is nothing
//!   to repair it *from*.
//! - A record is trusted only as far as its stored `api_identity` still matches
//!   the corpus, so a route that survived a rename is impossible rather than
//!   merely unlikely.
//!
//! Nothing here calls a model, opens a socket, or writes a byte a human cannot
//! read: the file is TAB-separated text, and `awk -F'\t'` is a supported way to
//! read it.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use super::digest::Digest;
use super::{TextError, TextResult, TEXT_FORMAT_VERSION};
use crate::lex::{split, stop};
use crate::result::Confidence;

/// Where the cache lives, repository-relative.
pub const ROUTES_PATH: &str = ".rr/ROUTES.md";

/// The most records the file may hold.
///
/// A bound rather than a policy: an agent asks tens of distinct questions of a
/// repository, not thousands, and an unbounded local file is a slow leak nobody
/// is watching. Eviction is by lowest confidence, which needs no clock and no
/// counter — see [`RouteTable::insert`].
pub const MAX_ROUTES: usize = 1024;

/// The frontmatter `type` of this artifact.
pub(crate) const ROUTES_TYPE: &str = "rr-routes";
/// The title line, fixed so a reader can recognise the file by its head.
pub(crate) const ROUTES_TITLE: &str = "# Routes";
/// The column legend, naming the separator rather than printing it.
pub(crate) const ROUTES_COLUMNS: &str =
    "<!-- columns: key<TAB>anchor<TAB>map<TAB>api_identity<TAB>confidence -->";

/// The banner a route cache of this format version carries.
///
/// A function rather than a constant, matching [`super::render::map_banner`]
/// and `symbols_banner`: the version is interpolated, and one spelling that
/// takes it as an argument is one fewer place for the number to go stale.
pub(crate) fn routes_banner(format: u32) -> String {
    format!("<!-- generated by rr format {format}; local, learned, and fully discardable -->")
}

/// The normalized form of one question.
///
/// Deliberately built from the query text alone. Building it from
/// [`crate::lex::query_terms`] instead would key the cache on the *corpus*:
/// that function drops any lexeme the index does not contain, so adding one
/// unrelated file would silently change the key of a question nobody re-asked,
/// and every route would miss. The `api_identity` in a record is what tracks
/// the index; the key tracks the question.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RouteKey(String);

impl RouteKey {
    /// The key for one raw query, or `None` when the query has no content.
    ///
    /// Sorted and deduplicated, not in the order the words were typed:
    /// `verify token` and `token verify` are one question, and filing them as
    /// two records that can then disagree is worse than filing neither.
    ///
    /// Stop words are dropped and stems are not taken. Dropping stop words is
    /// what [`crate::lex::query_terms`] already does, so the two agree about
    /// what a content word is. *Not* stemming is the deliberate half: a stem is
    /// chosen against the corpus, and it would delete the asker's own word from
    /// the one column a human greps.
    #[must_use]
    pub fn new(raw: &str) -> Option<Self> {
        let mut lexemes: Vec<String> = Vec::new();
        let _ = split::for_each_lexeme(raw, |lexeme| {
            if !stop::is_stop_word(lexeme) {
                lexemes.push(lexeme.to_owned());
            }
            Ok(())
        });
        lexemes.sort_unstable();
        lexemes.dedup();
        if lexemes.is_empty() {
            return None;
        }
        Some(Self(lexemes.join(" ")))
    }

    /// The key as the one string the file stores.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Whether a key read off disk is one this crate could have written.
    ///
    /// A predicate rather than an encoder, and that is the point: every lexeme
    /// the splitter yields is alphanumeric, NFC and lowercase, so a key can
    /// never contain the TAB that separates columns, nor a newline, nor `|`,
    /// `#` or `%`. Checking that on the way in is cheaper and stricter than
    /// escaping on the way out, and it means a key in the file is readable by a
    /// human without decoding.
    ///
    /// Strictly ascending rather than merely sorted, because [`Self::new`]
    /// deduplicates: a file holding `token token` was not written here.
    fn is_wellformed(raw: &str) -> bool {
        !raw.is_empty()
            && raw.split(' ').all(split::is_canonical_term)
            && raw.split(' ').is_sorted_by(|left, right| left < right)
    }
}

/// One learned route.
///
/// `anchor` is stored in the spelling `rr query` prints — the output of
/// [`crate::render::encode_anchor`], which is what follows
/// `FINAL SOURCE ANCHOR (copy exactly):`. Stored verbatim so a reader can paste
/// it back into `rr query` without knowing anything about this file.
///
/// There is deliberately **no line number here**, and that is not an omission.
/// Every field a record carries has to be one `api_identity` covers, or the
/// record can go wrong while still validating. `start_line` is one of the seven
/// things the scope `api_hash`es behind that identity exclude by construction,
/// so a stored line would keep pointing at the row a definition used to be on,
/// silently, for as long as nothing else in the repository changed. A caller
/// that wants a line asks `rr query`, which reads it out of the snapshot and so
/// cannot be stale.
#[derive(Debug, Clone, PartialEq)]
pub struct RouteRecord {
    /// The normalized question this route answers.
    pub key: RouteKey,
    /// The issue #7 source anchor, byte-for-byte as `rr query` prints it.
    pub anchor: String,
    /// The owning map, destination-encoded exactly as `.rr/SYMBOLS.md` stores
    /// it. Encoded and not raw because `RelPath::new("a\tb.md")` succeeds, and
    /// a tab here would invent a column.
    pub map: String,
    /// The corpus API identity this route was learned against. The whole
    /// invalidation contract is that this still equals
    /// [`super::MapCatalog::api_identity`] at read time.
    ///
    /// The corpus and not the owning scope, because a route is an answer about
    /// the whole index: a better-matching name appearing in *another* directory
    /// changes what the ranker would say while leaving this record's own scope
    /// untouched, and a per-scope key would keep serving the old answer.
    pub api_identity: Digest,
    /// What the ranker believed when it gave this answer.
    ///
    /// Written and read back exactly, which is a requirement and not a nicety:
    /// a hit replays this number into `rr query --json`, so a spelling that lost
    /// a digit would make two identical runs of one question print two different
    /// documents.
    pub confidence: Confidence,
}

/// Every route this repository has learned, keyed once per question.
///
/// A `BTreeMap` rather than a `HashMap`: the file is written in key order, and
/// a map that is already ordered means the writer has no sort step that could
/// be forgotten.
#[derive(Debug, Clone, Default)]
pub struct RouteTable {
    records: BTreeMap<RouteKey, RouteRecord>,
}

impl RouteTable {
    /// The route filed against this question, if one is.
    #[must_use]
    pub fn get(&self, key: &RouteKey) -> Option<&RouteRecord> {
        self.records.get(key)
    }

    /// How many questions this table answers.
    #[must_use]
    pub fn len(&self) -> usize {
        self.records.len()
    }

    /// Whether nothing has been learned yet.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.records.is_empty()
    }

    /// Every record, in the order the file stores them.
    pub fn records(&self) -> impl Iterator<Item = &RouteRecord> {
        self.records.values()
    }

    /// Records one route, replacing any previous answer to the same question.
    ///
    /// Replacement, not accumulation: this file answers "what did rr say last
    /// time", and two answers to one question would make the reader choose —
    /// which is the work a cache exists to remove.
    ///
    /// Returns `true` when the table changed, so a caller can skip a write.
    ///
    /// A record the bound immediately evicts leaves the table exactly as it
    /// was, so it reports no change: a full table plus one less-believed
    /// question must not rewrite [`MAX_ROUTES`] lines to say the same thing.
    /// Only a new key can overflow the bound — replacing an existing one keeps
    /// the length — so surviving the eviction is the whole test.
    pub fn insert(&mut self, record: RouteRecord) -> bool {
        if self.records.get(&record.key) == Some(&record) {
            return false;
        }
        let key = record.key.clone();
        self.records.insert(key.clone(), record);
        self.evict_to_bound();
        self.records.contains_key(&key)
    }

    /// Keeps only the records a predicate still believes in.
    ///
    /// Returns whether anything went, so `update_routes` can skip a write that
    /// would produce the bytes already on disk.
    pub fn retain<F>(&mut self, mut keep: F) -> bool
    where
        F: FnMut(&RouteRecord) -> bool,
    {
        let before = self.records.len();
        self.records.retain(|_, record| keep(record));
        before != self.records.len()
    }

    /// Drops the least-believed records until the table fits [`MAX_ROUTES`].
    ///
    /// Lowest confidence first, then greatest key by bytes so the choice is
    /// total and reproducible. Recency would be the better policy and is not
    /// available: it needs a clock or a counter written into the file, and
    /// either makes the bytes depend on something other than the routes — which
    /// is what the golden test exists to forbid.
    fn evict_to_bound(&mut self) {
        while self.records.len() > MAX_ROUTES {
            let Some(victim) = self
                .records
                .values()
                .min_by(|left, right| {
                    left.confidence
                        .get()
                        .total_cmp(&right.confidence.get())
                        .then_with(|| right.key.as_str().cmp(left.key.as_str()))
                })
                .map(|record| record.key.clone())
            else {
                return;
            };
            self.records.remove(&victim);
        }
    }
}

/// The bytes this table would be written as.
///
/// # Errors
/// Returns [`TextError::Record`] when a record would break the column grammar.
/// That is unreachable through [`RouteTable::insert`] — the key is a checked
/// [`RouteKey`], the anchor is percent-encoded and the map is
/// destination-encoded — and it is checked anyway, because "unreachable" is a
/// claim about today's callers and a silent extra column is a corrupt file that
/// reads back as a different route.
pub fn render_routes(table: &RouteTable) -> TextResult<Vec<u8>> {
    let mut body = String::new();
    body.push_str(&routes_banner(TEXT_FORMAT_VERSION));
    body.push('\n');
    body.push_str(ROUTES_TITLE);
    body.push('\n');
    body.push_str(ROUTES_COLUMNS);
    body.push('\n');
    for record in table.records.values() {
        let line = format!(
            "{}\t{}\t{}\t{}\t{:?}",
            record.key.as_str(),
            record.anchor,
            record.map,
            record.api_identity.to_text(),
            record.confidence.get()
        );
        if line.contains('\n') || line.matches('\t').count() != 4 {
            return Err(TextError::Record {
                reason: "a route record contains a tab or newline of its own",
            });
        }
        body.push_str(&line);
        body.push('\n');
    }

    let mut out = String::from("---\n");
    let _ = writeln!(out, "type: {ROUTES_TYPE:?}");
    let _ = writeln!(out, "format: {TEXT_FORMAT_VERSION}");
    let _ = writeln!(out, "routes: {}", table.records.len());
    out.push_str("---\n");
    out.push_str(&body);
    Ok(out.into_bytes())
}

/// Why a `.rr/ROUTES.md` could not be read.
///
/// Every variant leads to the same action — discard the file and start empty —
/// so this exists to be *reported*, not branched on. It is still a closed enum
/// rather than a bare `bool`, because "the cache reset" and "the cache reset
/// because something wrote a duplicate key into it" are different things for a
/// human reading `rr refresh --verbose`, and a free-form string would let that
/// text drift into a contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RouteFault {
    /// The bytes are not UTF-8.
    NotUtf8,
    /// The header is not the one this module writes.
    Frontmatter,
    /// A record line is not the supported grammar.
    Record,
    /// Two records answer the same question.
    DuplicateKey,
    /// Fewer or more records than the header declares.
    CountMismatch,
}

impl RouteFault {
    /// The published spelling, for a `--verbose` report.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::NotUtf8 => "not valid UTF-8",
            Self::Frontmatter => "the header is not the one rr writes",
            Self::Record => "a record is not the supported grammar",
            Self::DuplicateKey => "two records answer the same question",
            Self::CountMismatch => "the record count does not match the header",
        }
    }
}

/// Reads a `.rr/ROUTES.md`, or says why it could not.
///
/// Never returns a partial table. A file that fails anywhere fails entirely —
/// see [`RouteFault`] for why that is the whole error policy rather than the
/// first of several.
///
/// # Errors
/// Returns the [`RouteFault`] that stopped it. Nothing is repaired: there is
/// nothing to repair this file *from*.
pub fn parse_routes(bytes: &[u8]) -> Result<RouteTable, RouteFault> {
    let text = std::str::from_utf8(bytes).map_err(|_| RouteFault::NotUtf8)?;
    let mut lines = text.lines();

    if lines.next() != Some("---") {
        return Err(RouteFault::Frontmatter);
    }
    let mut declared: Option<usize> = None;
    let mut kind_seen = false;
    let mut format_seen = false;
    let mut closed = false;
    for line in lines.by_ref() {
        if line == "---" {
            closed = true;
            break;
        }
        match line.split_once(": ") {
            Some(("type", value)) => kind_seen = value.trim_matches('"') == ROUTES_TYPE,
            Some(("format", value)) => {
                format_seen = value.parse::<u32>().ok() == Some(TEXT_FORMAT_VERSION);
            }
            Some(("routes", value)) => declared = value.parse::<usize>().ok(),
            _ => return Err(RouteFault::Frontmatter),
        }
    }
    if !closed || !kind_seen || !format_seen {
        return Err(RouteFault::Frontmatter);
    }
    let Some(declared) = declared else {
        return Err(RouteFault::Frontmatter);
    };

    if lines.next() != Some(routes_banner(TEXT_FORMAT_VERSION).as_str())
        || lines.next() != Some(ROUTES_TITLE)
        || lines.next() != Some(ROUTES_COLUMNS)
    {
        return Err(RouteFault::Frontmatter);
    }

    let mut records = BTreeMap::new();
    for line in lines {
        let record = parse_route_record(line)?;
        if records.insert(record.key.clone(), record).is_some() {
            return Err(RouteFault::DuplicateKey);
        }
    }
    if records.len() != declared {
        return Err(RouteFault::CountMismatch);
    }
    Ok(RouteTable { records })
}

fn parse_route_record(line: &str) -> Result<RouteRecord, RouteFault> {
    let mut columns = line.split('\t');
    let (Some(key), Some(anchor), Some(map), Some(hash), Some(confidence), None) = (
        columns.next(),
        columns.next(),
        columns.next(),
        columns.next(),
        columns.next(),
        columns.next(),
    ) else {
        return Err(RouteFault::Record);
    };
    if !RouteKey::is_wellformed(key) {
        return Err(RouteFault::Record);
    }
    crate::render::decode_anchor(anchor).map_err(|_| RouteFault::Record)?;
    super::encode::decode_destination_component(map).map_err(|_| RouteFault::Record)?;
    let api_identity = Digest::parse(hash).map_err(|_| RouteFault::Record)?;
    let confidence = confidence
        .parse::<f32>()
        .ok()
        .and_then(|value| Confidence::new(value).ok())
        .ok_or(RouteFault::Record)?;

    Ok(RouteRecord {
        key: RouteKey(key.to_owned()),
        anchor: anchor.to_owned(),
        map: map.to_owned(),
        api_identity,
        confidence,
    })
}

/// The `map` column's spelling for one repository-relative path.
///
/// Exported so the command line can build a record without reaching into this
/// module's private encoder: the caller needs exactly this one function, not
/// the whole of [`super::encode`].
#[must_use]
pub fn encode_map_destination(path: &str) -> String {
    super::encode::destination(path, None)
}

/// Reads the cache, or an empty one.
///
/// Returns the fault alongside the table so a caller can report a reset; it
/// never returns an error, because a caller that cannot read its cache has not
/// failed at anything a user asked for.
#[must_use]
pub fn load_routes(root: &Path) -> (RouteTable, Option<RouteFault>) {
    match std::fs::read(root.join(ROUTES_PATH)) {
        Ok(bytes) => match parse_routes(&bytes) {
            Ok(table) => (table, None),
            Err(fault) => (RouteTable::default(), Some(fault)),
        },
        Err(_) => (RouteTable::default(), None),
    }
}

/// Runs `edit` against the cache with the routes lock held, and writes the
/// result if it changed.
///
/// The lock is what makes read-modify-write safe between two concurrent
/// `rr query` processes: without it the second reader's table is the first
/// reader's, and whichever writes last silently drops the other's route.
///
/// Deliberately **not** the publication guard. That one fails immediately when
/// it is already held, so a query taking it would fail outright whenever a
/// refresh happened to be running — a cache that can fail the operation it
/// exists to speed up. This lock blocks instead, and nothing takes the two in
/// opposite orders.
///
/// Returns what happened. Every failure is swallowed: see the module header on
/// why a cache write may not become a query failure.
pub fn update_routes<F>(root: &Path, edit: F) -> RouteUpdate
where
    F: FnOnce(&mut RouteTable) -> bool,
{
    let local = crate::workspace::local_dir(root);
    if std::fs::create_dir_all(&local).is_err() {
        return RouteUpdate::default();
    }
    let Ok(lock) = std::fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(false)
        .open(local.join("routes.lock"))
    else {
        return RouteUpdate::default();
    };
    if lock.lock().is_err() {
        return RouteUpdate::default();
    }
    let (mut table, fault) = load_routes(root);
    let changed = edit(&mut table);
    let wrote = (changed || fault.is_some()) && write_routes(root, &local, &table);
    let _ = lock.unlock();
    RouteUpdate { wrote, fault }
}

/// What one pass over the cache did.
///
/// A pair rather than a `bool`, because the two halves answer different
/// questions and only one of them is about this call: `wrote` says whether the
/// file on disk moved, and `fault` says the cache the caller *found* was
/// unreadable and has been reset. Dropping the second is what left
/// [`RouteFault`] as a closed enum nobody ever printed — a reset a user could
/// only detect by noticing every route was gone.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct RouteUpdate {
    /// Whether the file on disk was replaced.
    pub wrote: bool,
    /// Why the cache that was there had to be discarded, if it did.
    pub fault: Option<RouteFault>,
}

/// Replaces the file in one step.
///
/// Written to `.rr/local/routes.tmp` and renamed, not written in place: a torn
/// write leaves a file whose header disagrees with its records, and the reader
/// would throw the whole cache away for a crash that happened to land mid-line.
/// `.rr/local/` and `.rr/` are one filesystem by construction, so the rename is
/// atomic.
fn write_routes(root: &Path, local: &Path, table: &RouteTable) -> bool {
    let Ok(bytes) = render_routes(table) else {
        return false;
    };
    let temp = local.join("routes.tmp");
    if std::fs::write(&temp, &bytes).is_err() {
        return false;
    }
    if std::fs::rename(&temp, root.join(ROUTES_PATH)).is_err() {
        let _ = std::fs::remove_file(&temp);
        return false;
    }
    true
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    fn digest_of(text: &str) -> Digest {
        Digest::of_bytes(text.as_bytes())
    }

    fn record(key: &str, anchor: &str, confidence: f32) -> RouteRecord {
        RouteRecord {
            key: RouteKey::new(key).expect("a test key has content"),
            anchor: anchor.to_owned(),
            map: encode_map_destination("src/auth/MAP.md"),
            api_identity: digest_of("corpus"),
            confidence: Confidence::new(confidence).expect("a test confidence is in range"),
        }
    }

    #[test]
    fn a_key_is_the_same_for_three_spellings_of_one_name() {
        for raw in ["verify token", "verifyToken", "verify_token"] {
            assert_eq!(
                RouteKey::new(raw).unwrap().as_str(),
                "token verify",
                "{raw} keyed differently"
            );
        }
        assert_eq!(
            RouteKey::new("rotate signing key").unwrap().as_str(),
            "key rotate signing"
        );
        assert_eq!(
            RouteKey::new("Where IS the TOKEN verified?")
                .unwrap()
                .as_str(),
            "token verified"
        );
    }

    /// Amendment B: two spellings of one question are one record, so they can
    /// never file two answers that disagree.
    #[test]
    fn a_key_is_sorted_not_typed_in_order() {
        assert_eq!(RouteKey::new("verify token"), RouteKey::new("token verify"));
        assert_eq!(
            RouteKey::new("signing rotate key"),
            RouteKey::new("rotate signing key")
        );
    }

    #[test]
    fn a_key_of_only_stop_words_is_none() {
        assert!(RouteKey::new("the a of").is_none());
        assert!(RouteKey::new("").is_none());
        assert!(RouteKey::new("   ").is_none());
    }

    /// What licenses the absence of an encoder for the key column: no input,
    /// however hostile, produces a key that could invent a column or a line.
    #[test]
    fn a_key_never_contains_a_separator() {
        let hostile = [
            "verify\ttoken",
            "verify\ntoken",
            "verify\0token",
            "verify\u{7f}token",
            "verify|token#and%that",
            "ｖｅｒｉｆｙ ｔｏｋｅｎ",
            "café CAFÉ cafe\u{301}",
            "🔐 rotate 🔑 key",
            "---\ntype: \"rr-routes\"",
            "  \t\r\n  ",
        ];
        for raw in hostile {
            let Some(key) = RouteKey::new(raw) else {
                continue;
            };
            assert!(
                RouteKey::is_wellformed(key.as_str()),
                "{raw:?} produced a key this crate would refuse to read back: {:?}",
                key.as_str()
            );
            for forbidden in ['\t', '\n', '\r', '|', '#', '%', '\0'] {
                assert!(
                    !key.as_str().contains(forbidden),
                    "{raw:?} produced a key carrying {forbidden:?}"
                );
            }
        }
    }

    #[test]
    fn a_rendered_table_reparses_to_itself() {
        let mut table = RouteTable::default();
        assert!(table.insert(record(
            "verify token",
            "src/auth/token.rs#verify_token",
            1.0
        )));
        assert!(table.insert(record(
            "rotate signing key",
            "src/auth/keys.rs#rotate_signing_key",
            0.813_263
        )));

        let bytes = render_routes(&table).expect("render");
        let back = parse_routes(&bytes).expect("reparse");
        assert_eq!(back.len(), table.len());
        for original in table.records() {
            assert_eq!(back.get(&original.key), Some(original));
        }
        assert_eq!(render_routes(&back).expect("re-render"), bytes);
    }

    /// Exactly, not approximately: the number a hit replays into
    /// `rr query --json` is the number the ranker gave, so a run answered from
    /// the cache prints the same document as the run that filled it.
    #[test]
    fn a_confidence_survives_the_round_trip_bit_for_bit() {
        for raw in [
            0.0_f32,
            0.000_001,
            0.123_456,
            0.5,
            0.813_263_4,
            0.999_999_94,
            1.0,
        ] {
            let mut table = RouteTable::default();
            table.insert(record(
                "verify token",
                "src/auth/token.rs#verify_token",
                raw,
            ));
            let bytes = render_routes(&table).expect("render");
            let back = parse_routes(&bytes).expect("reparse");
            let key = RouteKey::new("verify token").unwrap();
            assert_eq!(
                back.get(&key).unwrap().confidence.get().to_bits(),
                raw.to_bits(),
                "{raw} did not survive the file"
            );
        }
    }

    /// A file cut short parses cleanly line by line and answers fewer questions
    /// than it claims to. Nothing partial is handed back.
    #[test]
    fn a_truncated_file_is_rejected_whole() {
        let mut table = RouteTable::default();
        table.insert(record(
            "verify token",
            "src/auth/token.rs#verify_token",
            1.0,
        ));
        table.insert(record(
            "rotate signing key",
            "src/auth/keys.rs#rotate_signing_key",
            0.5,
        ));
        let bytes = render_routes(&table).expect("render");
        let text = String::from_utf8(bytes).expect("utf8");
        let truncated: String =
            text.lines()
                .take(text.lines().count() - 1)
                .fold(String::new(), |mut out, line| {
                    out.push_str(line);
                    out.push('\n');
                    out
                });

        assert_eq!(
            parse_routes(truncated.as_bytes()).expect_err("a short file is a fault"),
            RouteFault::CountMismatch
        );
    }

    #[test]
    fn a_file_with_a_duplicate_key_is_rejected() {
        let mut table = RouteTable::default();
        table.insert(record(
            "verify token",
            "src/auth/token.rs#verify_token",
            1.0,
        ));
        let text = String::from_utf8(render_routes(&table).expect("render")).expect("utf8");
        let last = text.lines().next_back().expect("a record line").to_owned();
        let doubled = format!("{text}{last}\n").replace("routes: 1", "routes: 2");

        assert_eq!(
            parse_routes(doubled.as_bytes()).expect_err("two answers is a fault"),
            RouteFault::DuplicateKey
        );
    }

    #[test]
    fn a_record_with_a_bare_tab_in_the_map_column_does_not_render() {
        let mut table = RouteTable::default();
        let mut broken = record("verify token", "src/auth/token.rs#verify_token", 1.0);
        broken.map = "a\tb.md".to_owned();
        table.insert(broken);

        assert!(matches!(
            render_routes(&table),
            Err(TextError::Record { .. })
        ));
    }

    #[test]
    fn a_record_whose_anchor_does_not_decode_is_rejected() {
        let mut table = RouteTable::default();
        table.insert(record(
            "verify token",
            "src/auth/token.rs#verify_token",
            1.0,
        ));
        let text = String::from_utf8(render_routes(&table).expect("render")).expect("utf8");
        let broken = text.replace("verify_token", "verify%ZZtoken");

        assert_eq!(
            parse_routes(broken.as_bytes()).expect_err("a broken record is a fault"),
            RouteFault::Record
        );
    }

    #[test]
    fn a_key_that_is_not_canonical_is_rejected() {
        let mut table = RouteTable::default();
        table.insert(record(
            "verify token",
            "src/auth/token.rs#verify_token",
            1.0,
        ));
        let text = String::from_utf8(render_routes(&table).expect("render")).expect("utf8");
        let broken = text.replace("token verify\t", "verify token\t");

        assert_eq!(
            parse_routes(broken.as_bytes()).expect_err("a broken record is a fault"),
            RouteFault::Record
        );
    }

    #[test]
    fn eviction_drops_the_least_believed_route() {
        let mut table = RouteTable::default();
        for index in 0..=MAX_ROUTES {
            let step = u16::try_from(index).expect("the fixture stays under 65536 routes");
            let confidence = 0.1 + f32::from(step) / f32::from(u16::MAX);
            table.insert(record(
                &format!("question{index}"),
                "src/auth/token.rs#verify_token",
                confidence,
            ));
        }
        assert_eq!(table.len(), MAX_ROUTES);
        assert!(
            table.get(&RouteKey::new("question0").unwrap()).is_none(),
            "the least-believed record survived eviction"
        );
        assert!(
            table
                .get(&RouteKey::new(&format!("question{MAX_ROUTES}")).unwrap())
                .is_some(),
            "the most-believed record was evicted"
        );
    }

    /// No clock and no counter, so the same overflow evicts the same record
    /// every time — which is what lets the golden test be a golden test.
    #[test]
    fn eviction_is_deterministic_across_equal_confidences() {
        let build = || {
            let mut table = RouteTable::default();
            for index in 0..=MAX_ROUTES {
                table.insert(record(
                    &format!("question{index}"),
                    "src/auth/token.rs#verify_token",
                    0.5,
                ));
            }
            table
        };
        let first = build();
        let second = build();
        assert_eq!(
            render_routes(&first).expect("render"),
            render_routes(&second).expect("render")
        );
        assert_eq!(first.len(), MAX_ROUTES);
    }

    #[test]
    fn reinserting_an_identical_record_reports_no_change() {
        let mut table = RouteTable::default();
        let entry = record("verify token", "src/auth/token.rs#verify_token", 1.0);
        assert!(table.insert(entry.clone()));
        assert!(
            !table.insert(entry),
            "a repeated query must not rewrite the file"
        );
    }

    #[test]
    fn an_unreadable_cache_reads_as_empty_without_an_error() {
        let temp = tempfile::tempdir().expect("tempdir");
        std::fs::create_dir_all(temp.path().join(".rr")).expect("state dir");
        std::fs::write(temp.path().join(ROUTES_PATH), b"not a routes file\n").expect("write");

        let (table, fault) = load_routes(temp.path());
        assert!(table.is_empty());
        assert_eq!(fault, Some(RouteFault::Frontmatter));

        std::fs::write(temp.path().join(ROUTES_PATH), [0xFF, 0xFE]).expect("write");
        let (table, fault) = load_routes(temp.path());
        assert!(table.is_empty());
        assert_eq!(fault, Some(RouteFault::NotUtf8));
    }

    #[test]
    fn a_missing_cache_is_not_a_fault() {
        let temp = tempfile::tempdir().expect("tempdir");
        let (table, fault) = load_routes(temp.path());
        assert!(table.is_empty());
        assert_eq!(fault, None);
    }

    #[test]
    fn an_update_writes_through_the_lock_and_reads_back() {
        let temp = tempfile::tempdir().expect("tempdir");
        let wrote = update_routes(temp.path(), |table| {
            table.insert(record(
                "verify token",
                "src/auth/token.rs#verify_token",
                1.0,
            ))
        });
        assert!(wrote.wrote);

        let (table, fault) = load_routes(temp.path());
        assert_eq!(fault, None);
        assert_eq!(table.len(), 1);
        let wrote_again = update_routes(temp.path(), |table| {
            table.insert(record(
                "verify token",
                "src/auth/token.rs#verify_token",
                1.0,
            ))
        });
        assert!(!wrote_again.wrote);
    }

    #[test]
    fn retaining_reports_whether_anything_went() {
        let mut table = RouteTable::default();
        table.insert(record(
            "verify token",
            "src/auth/token.rs#verify_token",
            1.0,
        ));
        assert!(!table.retain(|_| true));
        assert!(table.retain(|_| false));
        assert!(table.is_empty());
    }
}
